name: RDP via Cloudflare Tunnel
on: workflow_dispatch

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP & Firewall
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          netsh advfirewall firewall add rule name="RDP-Allow" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force

      - name: Create RDP User
        run: |
          $pwd = "admin@123"
          $sec = ConvertTo-SecureString $pwd -AsPlainText -Force
          if (-not (Get-LocalUser -Name "TOOLBOXLAP" -ErrorAction SilentlyContinue)) {
            New-LocalUser -Name "TOOLBOXLAP" -Password $sec -AccountNeverExpires
          }
          Add-LocalGroupMember -Group "Administrators" -Member "TOOLBOXLAP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "TOOLBOXLAP"

      - name: Install cloudflared
        run: |
          Invoke-WebRequest -Uri "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.msi" -OutFile cloudflared.msi
          Start-Process msiexec.exe -ArgumentList '/i cloudflared.msi /quiet /norestart' -Wait
          Remove-Item cloudflared.msi -Force

      - name: Start cloudflared (using secret)
        env:
          TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
          TUNNEL_ID: b3ac50fc-16ee-4391-9186-e8559de41982
        run: |
          # register connector with token
          & "$env:ProgramFiles\cloudflared\cloudflared.exe" service install $env:TUNNEL_TOKEN
          Start-Sleep -Seconds 5
          # run tunnel by ID
          Start-Process "$env:ProgramFiles\cloudflared\cloudflared.exe" -ArgumentList "tunnel","run",$env:TUNNEL_ID -NoNewWindow
          Start-Sleep -Seconds 8

      - name: Verify local RDP
        run: |
          $t = Test-NetConnection -ComputerName localhost -Port 3389
          if (-not $t.TcpTestSucceeded) { Write-Error "RDP not listening"; exit 1 }
          Write-Host "✅ RDP listening"

      - name: Show info & keep alive
        run: |
          Write-Host "RDP at rdp1.elwe.qzz.io — user TOOLBOXLAP / admin@123"
          while ($true) { Write-Host "alive"; Start-Sleep -Seconds 300 }          TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
        run: |
          Write-Host "🚀 Installing Cloudflare Tunnel service..."
          & "$env:ProgramFiles\cloudflared.exe" service install $env:TUNNEL_TOKEN
          Start-Sleep -Seconds 5

          Write-Host "🔄 Starting tunnel..."
          Start-Process "$env:ProgramFiles\cloudflared.exe" -ArgumentList "tunnel","run",$env:TUNNEL_ID -NoNewWindow
          Start-Sleep -Seconds 10

          Write-Host "✅ Cloudflare tunnel started successfully!"

      - name: Verify RDP Port
        run: |
          $check = Test-NetConnection -ComputerName "localhost" -Port 3389
          if (-not $check.TcpTestSucceeded) {
            Write-Error "❌ RDP not listening on port 3389"
            exit 1
          }
          Write-Host "✅ RDP port 3389 is open and ready."

      - name: Display Info and Keep Alive
        run: |
          Write-Host ""
          Write-Host "==========================================="
          Write-Host "✅ RDP ACCESS READY"
          Write-Host "🌐 Address: rdp1.qzz.io"
          Write-Host "👤 Username: TOOLBOXLAP"
          Write-Host "🔑 Password: admin@123"
          Write-Host "==========================================="
          Write-Host "⚠️  Leave this workflow running to keep RDP alive."
          Write-Host "   Stop the job from GitHub Actions to disconnect."
          Write-Host "-------------------------------------------"
          while ($true) {
            Write-Host "[$(Get-Date)] RDP session active..."
            Start-Sleep -Seconds 300
          }
